### ISSUE TITLE
Inconsistent "Runtime Error: Event loop is closed" 

### ISSUE THREAD

**Issue by rossmacarthur** [klen/pytest-aio#7]
Hi, thanks for this library. I am hoping to migrate away from `pytest-asyncio` because of recent changes there.

I am using the `aiolib` fixture like this:

```python
@pytest.fixture(scope="session")
def aiolib() -> tuple[str, dict[str, Any]]:
    return "asyncio", {"use_uvloop": False}
```

However, I get the following exception.

```
platform darwin -- Python 3.11.7, pytest-8.0.2, pluggy-1.4.0 --~/.pyenv/versions/3.11.7/envs/bikeshed/bin/python
cachedir: .pytest_cache
Using --randomly-seed=657316342
configfile: pyproject.toml
plugins: aio-1.5.0, unordered-0.5.2, anyio-4.3.0, env-1.1.3, randomly-3.15.0, cov-4.1.0, icdiff-0.9, ddtrace-2.7.0, xdist-3.5.0
collected 562 items      

# many tests

--- Logging error ---
Traceback (most recent call last):
  File "~/.pyenv/versions/3.11.7/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/tasks.py", line 141, in __del__
    self._loop.call_exception_handler(context)
  File "~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 1797, in call_exception_handler
    self.default_exception_handler(context)
  File "~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 1771, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
Message: "Task was destroyed but it is pending!\ntask: <AsyncioContextTask pending name='Task-pytest-aio-367' coro=<<async_generator_asend without __name__>()>>"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "~/.pyenv/versions/3.11.7/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/tasks.py", line 141, in __del__
    self._loop.call_exception_handler(context)
  File "~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 1797, in call_exception_handler
    self.default_exception_handler(context)
  File "~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 1771, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
Message: "Task was destroyed but it is pending!\ntask: <AsyncioContextTask pending name='Task-pytest-aio-471' coro=<<async_generator_asend without __name__>()>>"
Arguments: ()
__________________________________________________ ERROR at teardown of test_redacted ___________________________________________________
[gw3] darwin -- Python 3.11.7 ~/.pyenv/versions/3.11.7/envs/bikeshed/bin/python

aiolib = ('asyncio', {'use_uvloop': False}), args = (), kwargs = {}, lib = 'asyncio', params = {'use_uvloop': False}
runner = <pytest_aio.runners.AsyncioRunner object at 0x29e91a950>, gen = <async_generator object _admin_test_client at 0x2ab2fd460>

    def wrapper(*args, aiolib, **kwargs):
        lib, params = aiolib
        if "aiolib" in argnames:
            kwargs["aiolib"] = aiolib
    
        with get_runner(lib, **params) as runner:
            if iscoroutinefunction(func):
                yield runner.run(func, *args, **kwargs)
                return
    
            gen = func(*args, **kwargs)
            try:
                yield runner.run(gen.__anext__().__await__)
            except StopAsyncIteration:
                raise RuntimeError("Async generator did not yield")
    
            try:
>               runner.run(gen.__anext__().__await__)

~/.pyenv/versions/3.11.7/envs/bikeshed/lib/python3.11/site-packages/pytest_aio/plugin.py:116: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
~/.pyenv/versions/3.11.7/envs/bikeshed/lib/python3.11/site-packages/pytest_aio/runners.py:69: in run
    task = AsyncioContextTask(fn(*args, **kwargs), self.ctx, self._loop)
~/.pyenv/versions/3.11.7/envs/bikeshed/lib/python3.11/site-packages/pytest_aio/utils.py:46: in __init__
    self._loop.call_soon(self._Task__step, context=self._context)
~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py:761: in call_soon
    self._check_closed()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=True debug=False>

    def _check_closed(self):
        if self._closed:
>           raise RuntimeError('Event loop is closed')
E           RuntimeError: Event loop is closed

~/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py:519: RuntimeError
```

It happens on a different tests every time (I am using `pytest-randomly`), and always at the end, usually 2-3 tests. It doesn't seem to be related to pytest-xdist runners because it happens when I run it without multiple workers.

Do you have any insights?

**Comment by rossmacarthur** [comment]
Not sure if this was fixed but we were able to migrate to `pytest-aio` more recently without any of these issues again. We are using the following session wide fixture.

```python
@pytest.fixture(scope="session")
def aiolib() -> tuple[str, dict[str, Any]]:
    return "asyncio", {"use_uvloop": False}
```
