### ISSUE TITLE
`pytest-aio` does not support `pytest-xdist`

### ISSUE THREAD

**Issue by harshil21** [klen/pytest-aio#8]
Hi, thanks for the library! I've been trying to run my test suite with this library and it worked perfectly on a single core. However if I want to use `pytest-xdist`, then all my tests pass, but the last test fails at teardown and throws the error `RuntimeError: Event loop is closed`. 

It would be great if support for `pytest-xdist` was added.

Python version: 3.12.3
pytest-aio: 1.8.1
pytest: 8.2.0

Used with `--dist=load` and `--dist=worksteal`
Installed plugins: flaky-3.8.1, testmon-2.1.1, anyio-4.3.0, aio-1.8.1, xdist-3.6.1

<details> 
<summary> Traceback </summary>

```
[gw5] linux -- Python 3.12.3 /home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/bin/python
  + Exception Group Traceback (most recent call last):
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
  |     result: Optional[TResult] = func()
  |                                 ^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/flaky/flaky_pytest_plugin.py", line 146, in <lambda>
  |     lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  |             ^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
  |     raise exception.with_traceback(exception.__traceback__)
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
  |     teardown.throw(exception)  # type: ignore[union-attr]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/threadexception.py", line 92, in pytest_runtest_teardown
  |     yield from thread_exception_runtest_hook()
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/threadexception.py", line 63, in thread_exception_runtest_hook
  |     yield
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
  |     teardown.throw(exception)  # type: ignore[union-attr]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 95, in pytest_runtest_teardown
  |     yield from unraisable_exception_runtest_hook()
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 65, in unraisable_exception_runtest_hook
  |     yield
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
  |     teardown.throw(exception)  # type: ignore[union-attr]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/logging.py", line 857, in pytest_runtest_teardown
  |     yield from self._runtest_for(item, "teardown")
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/logging.py", line 833, in _runtest_for
  |     yield
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
  |     teardown.throw(exception)  # type: ignore[union-attr]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/capture.py", line 883, in pytest_runtest_teardown
  |     return (yield)
  |             ^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
  |     res = hook_impl.function(*args)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/runner.py", line 188, in pytest_runtest_teardown
  |     item.session._setupstate.teardown_exact(nextitem)
  |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/runner.py", line 555, in teardown_exact
  |     raise exceptions[0]
  | ExceptionGroup: errors while tearing down <Session  exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=3358> (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/runner.py", line 544, in teardown_exact
    |     fin()
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/fixtures.py", line 1020, in finish
    |     raise exceptions[0]
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/fixtures.py", line 1009, in finish
    |     fin()
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/fixtures.py", line 893, in _teardown_yield_fixture
    |     next(it)
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pytest_aio/plugin.py", line 118, in wrapper
    |     runner.run(gen.__anext__().__await__)
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pytest_aio/runners.py", line 69, in run
    |     task = AsyncioContextTask(fn(*args, **kwargs), self.ctx, self._loop)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pytest_aio/utils.py", line 41, in __init__
    |     self._loop.call_soon(self._Task__step, context=self._context)
    |   File "/home/hoppingturtles/.local/share/mise/installs/python/3.12.3/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    |     self._check_closed()
    |   File "/home/hoppingturtles/.local/share/mise/installs/python/3.12.3/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    |     raise RuntimeError('Event loop is closed')
    | RuntimeError: Event loop is closed
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/runner.py", line 544, in teardown_exact
    |     fin()
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/fixtures.py", line 1020, in finish
    |     raise exceptions[0]
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/fixtures.py", line 1009, in finish
    |     fin()
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/_pytest/fixtures.py", line 893, in _teardown_yield_fixture
    |     next(it)
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pytest_aio/plugin.py", line 118, in wrapper
    |     runner.run(gen.__anext__().__await__)
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pytest_aio/runners.py", line 69, in run
    |     task = AsyncioContextTask(fn(*args, **kwargs), self.ctx, self._loop)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoppingturtles/Documents/pyprojects/python-telegram-bot/.venv/lib/python3.12/site-packages/pytest_aio/utils.py", line 41, in __init__
    |     self._loop.call_soon(self._Task__step, context=self._context)
    |   File "/home/hoppingturtles/.local/share/mise/installs/python/3.12.3/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    |     self._check_closed()
    |   File "/home/hoppingturtles/.local/share/mise/installs/python/3.12.3/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    |     raise RuntimeError('Event loop is closed')
    | RuntimeError: Event loop is closed
    +------------------------------------
```
</details>

**Comment by klen** [comment]
Works fine for me. Please check it again.
